{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.bc250-cu-live-manager;

  defaultPackage = pkgs.callPackage ./package.nix {};

  masksCsv = lib.concatMapStringsSep "," (mask:
    if lib.isInt mask then toString mask else mask
  ) cfg.boot.masks;

  configText = ''
    # BC-250 live manager boot profile.
    # Generated by NixOS.
    # Format: SE0.SH0,SE0.SH1,SE1.SH0,SE1.SH1 SPI WGP masks.
    BC250_WGP_MASKS=${masksCsv}
    UMR_ASIC=${cfg.umrAsic}
    UMR_INSTANCE=${cfg.umrInstance}
    UMR=${lib.getExe' pkgs.umr "umr"}
  '';
in
{
  options.services.bc250-cu-live-manager = {
    enable = lib.mkEnableOption "BC-250 CU Live Manager";

    package = lib.mkOption {
      type = lib.types.package;
      default = defaultPackage;
      description = "Package providing bc250-cu-live-manager.";
    };

    umrAsic = lib.mkOption {
      type = lib.types.str;
      default = "cyan_skillfish.gfx1013";
      description = "UMR ASIC selector used by bc250-cu-live-manager.";
    };

    umrInstance = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Optional UMR DRI instance. Empty means auto-detect on each service start.";
    };

    boot = {
      enable = lib.mkEnableOption "applying a saved BC-250 WGP table at boot";

      masks = lib.mkOption {
        type = lib.types.listOf (lib.types.oneOf [ lib.types.int lib.types.str ]);
        default = [ "0x1f" "0x1f" "0x1f" "0x1f" ];
        description = ''
          WGP masks to apply at boot in SE0.SH0, SE0.SH1, SE1.SH0, SE1.SH1 order.
          0x1f routes all five WGPs in a row, so the default is full 40 CU dispatch.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = lib.length cfg.boot.masks == 4;
        message = "services.bc250-cu-live-manager.boot.masks must contain exactly four masks.";
      }
    ];

    environment.systemPackages = [
      cfg.package
      pkgs.umr
    ];

    environment.etc."bc250-cu-live-manager.conf" = lib.mkIf cfg.boot.enable {
      text = configText;
      mode = "0644";
    };

    systemd.services.bc250-cu-live-manager = lib.mkIf cfg.boot.enable {
      description = "BC-250 CU saved enumeration and dispatch";
      after = [ "systemd-udev-settle.service" ];
      wants = [ "systemd-udev-settle.service" ];
      wantedBy = [ "multi-user.target" ];

      serviceConfig = {
        Type = "oneshot";
        EnvironmentFile = "-/etc/bc250-cu-live-manager.conf";
        ExecStartPre = "${lib.getExe pkgs.bash} -c 'for _ in {1..30}; do compgen -G \"/dev/dri/renderD*\" >/dev/null && exit 0; sleep 1; done; exit 1'";
        ExecStart = "${lib.getExe cfg.package} --yes apply-service";
        RemainAfterExit = true;
      };
    };
  };
}
